### ISSUE TITLE
Incorrect desktop icon installation location

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.ktechpit.ultimate-media-downloader#1]
The correct location of the desktop icon should be `${FLATPAK_DEST}/share/icons/hicolor/128x128/apps/`.

**Comment by hfiguiere** [comment]
the line should be removed. It escaped the review.

**Comment by hfiguiere** [comment]
it's not fixed, the MR was merge without building and it failed.

**Comment by AsciiWolf** [comment]
This may be the same problem as https://github.com/flathub/in.srev.guiscrcpy/pull/5#issuecomment-1154985644.

**Comment by hfiguiere** [comment]
not it's not.

the desktop file was copied into `/share/application` (no `s`).

As for that bug you mention it's because it should use `rename-desktop-file` instead of copying and renaming.
