### ISSUE TITLE
No screenshots in listing page

### ISSUE THREAD

**Issue by keshavbhatt** [flathub/com.ktechpit.ultimate-media-downloader#7]
Screenshots are not visible in flathub listing page, 
https://flathub.org/apps/com.ktechpit.ultimate-media-downloader

@hfiguiere can you help?
Thanks

**Comment by hfiguiere** [comment]
they are. not sure what you want from me.

**Comment by keshavbhatt** [comment]
@hfiguiere , Yes now they are visible. Maybe because i triggered a rebuild. 
Sorry to bother you.
